<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Fideos game">
    <meta name="author" content="Stan Gumeniuk">

    <title>Fideos</title>

    <!-- Bootstrap Core CSS -->
    <!--    <link href="/game/css/bootstrap.min.css" rel="stylesheet">-->

    <!-- Custom CSS -->
    <link href="/game/css/main.css?<?php rand(0, 10000); ?>" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="/js/jquery.js"></script>
    <script src="/game/js/main.js?<?php rand(0, 10000); ?>"></script>

</head>

<body>


<div class="header">
    <div class="header-container">header</div>
</div>

<div class="container">


    <div class="divgametable">
        <table class="gametable" id="gametable">
            <?php  (isset($gameTable)) ? $gameTableOk = $gameTable : $gameTableOk = array(
                '1' => array('1' => "", '2' => "", '3' => "", '4' => "", '5' => ""),
                '2' => array('1' => "", '2' => "", '3' => "", '4' => "", '5' => ""),
                '3' => array('1' => "", '2' => "", '3' => "", '4' => "", '5' => ""),
                '4' => array('1' => "", '2' => "", '3' => "", '4' => "", '5' => ""),
                '5' => array('1' => "", '2' => "", '3' => "", '4' => "", '5' => ""),
            ); ?>


            <tbody>
            <?php foreach ($gameTableOk as $rowNumber => $row): ?>
                <tr>
                    <?php foreach ($row as $cellNumber => $cell): ?>
                        <td id="gametable-cell-<?=$rowNumber;?>-<?=$cellNumber;?>">

                            <div class="gametable-input hidden">
                                <input type="text" maxlength="1" class="gametable" value="<?= $cell; ?>">
                            </div>
                            <div class="gametable-cell">
                                <?= $cell; ?>
                            </div>
                        </td>
                    <?php endforeach; ?>


                </tr>
            <?php endforeach; ?>


            </tbody>
        </table>
    </div>

    <footer>
        <div class="footer">
            <p>Copyright &copy; Stan Gumeniuk 2015</p>
        </div>
    </footer>


</div>


<div class="profiler"></div>


</body>
</html>


